### ISSUE TITLE
Problems install - frantz/generator

### ISSUE THREAD

**Issue by cymonbr** [kati-frantz/Laravel-5.3-and-Vue-js-2.0-social-network#7]
In composer update return a problem with frantz/generator

**Problem 1**
    - The requested package _frantz/generator_ could not be found in any version, there may be a typo in the package name.

**Potential causes:**
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see _<https://getcomposer.org/doc/04-schema.md#minimum-stability>_ for more details.

Read _<https://getcomposer.org/doc/articles/troubleshooting.md>_ for further common problems.

**Comment by bahdcoder** [comment]
I'm sorry , but the development of this package was actually suspended.

**Comment by ghost** [comment]
Yeh, that's way is a bad practice to use the code on GitHub.
@bahdcoder  Close the project if is not working!
